--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/artulloss/FilterX
branches:
- master
projects:
  FilterX:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.3.0
...
